import type { Metadata } from 'next';
import './globals.css';
import { Header } from '@/components/shared/header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='max-w-[1448px] mx-auto'>
        <Header />
        <main className='min-h-screen'>{children}</main>
      </body>
    </html>
  );
}
